export const mockResponse = {
    "login": "trollord",
    "id": 80673827,
    "node_id": "MDQ6VXNlcjgwNjczODI3",
    "avatar_url": "https://avatars.githubusercontent.com/u/80673827?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/trollord",
    "html_url": "https://github.com/trollord",
    "followers_url": "https://api.github.com/users/trollord/followers",
    "following_url": "https://api.github.com/users/trollord/following{/other_user}",
    "gists_url": "https://api.github.com/users/trollord/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/trollord/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/trollord/subscriptions",
    "organizations_url": "https://api.github.com/users/trollord/orgs",
    "repos_url": "https://api.github.com/users/trollord/repos",
    "events_url": "https://api.github.com/users/trollord/events{/privacy}",
    "received_events_url": "https://api.github.com/users/trollord/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Mandar Kasangottuwar",
    "company": null,
    "blog": "",
    "location": null,
    "email": null,
    "hireable": null,
    "bio": null,
    "twitter_username": null,
    "public_repos": 19,
    "public_gists": 0,
    "followers": 7,
    "following": 9,
    "created_at": "2021-03-15T07:58:14Z",
    "updated_at": "2024-02-07T07:48:56Z"
}